source 'https://rubygems.org'
gem 'sinatra', '1.4.6'
gem 'sinatra-contrib', '1.4.2'
gem 'sinatra-flash', '0.3.0', require: 'sinatra/flash'
gem 'bcrypt-ruby', '3.0.1'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'dm-mysql-adapter', '1.2.0'
gem 'warden', '1.2.3'
gem 'shotgun', '0.9.1'
gem 'sinatra-logger'
gem 'do_mysql', '0.10.16'
